version: 2.1
orbs:
  architect: giantswarm/architect@4.6.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push workadventure chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "workadventure"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
